# Generated by Django 3.2 on 2021-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=16)),
                ('brand_name', models.CharField(max_length=32)),
                ('mutual', models.CharField(max_length=32)),
                ('franchise_start_date', models.CharField(max_length=20)),
                ('franchise_months', models.IntegerField()),
                ('num_of_franchise', models.IntegerField()),
                ('num_of_employees', models.IntegerField()),
                ('num_of_open', models.IntegerField()),
                ('num_of_quit', models.IntegerField()),
                ('num_of_cancel', models.IntegerField()),
                ('num_of_name_changing', models.IntegerField()),
                ('average_sales', models.IntegerField()),
                ('average_sales_per_area', models.IntegerField()),
                ('franchise_fee', models.IntegerField()),
                ('education_fee', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('other_cost', models.IntegerField()),
                ('startup_cost', models.IntegerField()),
                ('cost_per_area', models.IntegerField()),
                ('standard_area', models.IntegerField()),
                ('total_cost', models.IntegerField()),
            ],
        ),
    ]
