# Generated by Django 3.2 on 2021-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='brand',
            name='franchise_start_date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='brand',
            name='mutual',
            field=models.CharField(max_length=40),
        ),
    ]
