# Generated by Django 3.2 on 2021-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_brand_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('mutual', models.CharField(max_length=40)),
                ('representative', models.CharField(max_length=40)),
                ('register_law_date', models.CharField(max_length=40)),
                ('register_biz_date', models.CharField(max_length=40)),
                ('representative_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('biz_type', models.CharField(max_length=40)),
                ('law_number', models.CharField(max_length=40)),
                ('biz_number', models.CharField(max_length=40)),
                ('assets_2020', models.IntegerField()),
                ('liabilities_2020', models.IntegerField()),
                ('equity_2020', models.IntegerField()),
                ('sales_2020', models.IntegerField()),
                ('income_2020', models.IntegerField()),
                ('net_income_2020', models.IntegerField()),
                ('assets_2019', models.IntegerField()),
                ('liabilities_2019', models.IntegerField()),
                ('equity_2019', models.IntegerField()),
                ('sales_2019', models.IntegerField()),
                ('income_2019', models.IntegerField()),
                ('net_income_2019', models.IntegerField()),
                ('assets_2018', models.IntegerField()),
                ('liabilities_2018', models.IntegerField()),
                ('equity_2018', models.IntegerField()),
                ('sales_2018', models.IntegerField()),
                ('income_2018', models.IntegerField()),
                ('net_income_2018', models.IntegerField()),
                ('assets_2017', models.IntegerField()),
                ('liabilities_2017', models.IntegerField()),
                ('equity_2017', models.IntegerField()),
                ('sales_2017', models.IntegerField()),
                ('income_2017', models.IntegerField()),
                ('net_income_2017', models.IntegerField()),
                ('opening_2020', models.IntegerField()),
                ('closing_2020', models.IntegerField()),
                ('name_change_2020', models.IntegerField()),
                ('opening_2019', models.IntegerField()),
                ('closing_2019', models.IntegerField()),
                ('name_change_2019', models.IntegerField()),
                ('opening_2018', models.IntegerField()),
                ('closing_2018', models.IntegerField()),
                ('name_change_2018', models.IntegerField()),
                ('opening_2017', models.IntegerField()),
                ('closing_2017', models.IntegerField()),
                ('name_change_2017', models.IntegerField()),
                ('num_of_correction', models.IntegerField()),
                ('num_loss_of_law', models.IntegerField()),
                ('num_of_sentences', models.IntegerField()),
            ],
        ),
    ]
