# Generated by Django 3.2 on 2021-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_headquarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
