# Generated by Django 3.2 on 2021-05-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210429_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('do', models.CharField(max_length=16)),
                ('sigu', models.CharField(max_length=32)),
                ('dong', models.CharField(max_length=16)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
