# Generated by Django 3.2 on 2021-05-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=16)),
                ('brand_name', models.CharField(max_length=40)),
                ('do', models.CharField(max_length=16)),
                ('sigu', models.CharField(max_length=32)),
                ('dong', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
                ('latitude', models.CharField(max_length=16)),
            ],
        ),
    ]
